In [1]:
# one hot encoding

In [2]:
# housing iteration 3

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

housing_maindf = pd.read_csv('~/Documents/datacamp/WBS-School/wbs-housing-iter-0-2/iter-3/housing-classification-iter3.csv')

housing_df = housing_maindf.copy()

In [4]:
# housing_df.info()

In [5]:
X = housing_df.copy()

In [6]:
# target
y = X.pop("Expensive")

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=31416)

In [8]:
# imputing train set

In [9]:
# helper
def to_df(arr,df):
    print(arr.shape)
    print(df.shape)
    return pd.DataFrame(arr, columns=df.columns, index=df.index)

In [10]:
from sklearn.impute import SimpleImputer

# selecting non-numerical columns
X_train_cat = X_train.select_dtypes(exclude="number")

# defining the imputer to use "N_A" as replacement value
cat_imputer = SimpleImputer(strategy="constant", 
                            fill_value="N_A")#.set_output(transform='pandas')

# fitting and transforming
X_cat_imputed = cat_imputer.fit_transform(X_train_cat)
X_cat_imputed = to_df(X_cat_imputed,X_train_cat)

(1168, 6)
(1168, 6)

In [11]:
# Selecting numerical columns
X_train_num = X_train.select_dtypes(include="number")

# Imputing the mean
num_imputer = SimpleImputer(strategy="mean")#.set_output(transform='pandas')

# Fitting and transforming
X_num_imputed = num_imputer.fit_transform(X_train_num)
X_num_imputed = to_df(X_num_imputed,X_train_num)
X_num_imputed.head()

(1168, 9)
(1168, 9)

,LotArea,LotFrontage,TotalBsmtSF,BedroomAbvGr,Fireplaces,PoolArea,GarageCars,WoodDeckSF,ScreenPorch
772,7819.0,94.00000,1029.0,3.0,1.0,0.0,2.0,144.0,0.0
157,12003.0,92.00000,774.0,4.0,1.0,0.0,3.0,0.0,0.0
360,7540.0,70.10352,888.0,2.0,1.0,0.0,2.0,0.0,192.0
744,5395.0,41.00000,1337.0,2.0,1.0,0.0,2.0,96.0,0.0
150,10356.0,120.00000,969.0,3.0,0.0,0.0,2.0,0.0,0.0

In [12]:
# Concatenating all columns
X_imputed = pd.concat([X_cat_imputed, X_num_imputed], axis=1)

X_imputed.head()

,MSZoning,Condition1,Heating,Street,CentralAir,Foundation,LotArea,LotFrontage,TotalBsmtSF,BedroomAbvGr,Fireplaces,PoolArea,GarageCars,WoodDeckSF,ScreenPorch
772,RL,Norm,GasA,Pave,Y,CBlock,7819.0,94.00000,1029.0,3.0,1.0,0.0,2.0,144.0,0.0
157,RL,Norm,GasA,Pave,Y,PConc,12003.0,92.00000,774.0,4.0,1.0,0.0,3.0,0.0,0.0
360,RL,Norm,GasA,Pave,Y,CBlock,7540.0,70.10352,888.0,2.0,1.0,0.0,2.0,0.0,192.0
744,RL,Norm,GasA,Pave,Y,PConc,5395.0,41.00000,1337.0,2.0,1.0,0.0,2.0,96.0,0.0
150,RL,Norm,GasA,Pave,Y,CBlock,10356.0,120.00000,969.0,3.0,0.0,0.0,2.0,0.0,0.0

In [13]:
# apply one hot encoder

In [14]:
from sklearn.preprocessing import OneHotEncoder

# initialize
# my_onehot = OneHotEncoder(drop="first",sparse_output=False).set_output(transform='pandas')
my_onehot = OneHotEncoder()
# fit
my_onehot.fit(X_cat_imputed)

# transform
X_cat_imputed_mat = my_onehot.transform(X_cat_imputed)

In [15]:
# X_cat_imputed_onehot = to_df(X_cat_imputed_onehot)
import scipy.sparse
X_cat_imputed_onehot = pd.DataFrame.sparse.from_spmatrix(X_cat_imputed_mat)

In [16]:
X_imputed = pd.concat([X_cat_imputed_onehot, X_num_imputed], axis=1)

X_imputed.head(3)

,0,1,2,3,4,5,6,7,8,9,...,28,LotArea,LotFrontage,TotalBsmtSF,BedroomAbvGr,Fireplaces,PoolArea,GarageCars,WoodDeckSF,ScreenPorch
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,8450.0,65.0,856.0,3.0,0.0,0.0,2.0,0.0,0.0
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,9600.0,80.0,1262.0,3.0,1.0,0.0,2.0,298.0,0.0
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,11250.0,68.0,920.0,3.0,1.0,0.0,2.0,0.0,0.0

In [17]:
# setup pipeline

In [18]:
from sklearn.pipeline import make_pipeline

# select categorical and numerical column names
X_cat_columns = X.select_dtypes(exclude="number").copy().columns
X_num_columns = X.select_dtypes(include="number").copy().columns

# create numerical pipeline, only with the SimpleImputer(strategy="mean")
numeric_pipe = make_pipeline(
    SimpleImputer(strategy="mean"))
 
 # create categorical pipeline, with the SimpleImputer(fill_value="N_A") and the OneHotEncoder
categoric_pipe = make_pipeline(
    SimpleImputer(strategy="constant", fill_value="N_A"),
    # OneHotEncoder(sparse_output=False)
    OneHotEncoder()
)

In [19]:
# initialize transformer

In [20]:
from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer(
    transformers=[
        ("num_pipe", numeric_pipe, X_num_columns),
        ("cat_pipe", categoric_pipe, X_cat_columns),
    ]
)

In [21]:
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier

In [23]:
from sklearn.model_selection import GridSearchCV

dtclass = DecisionTreeClassifier()

full_pipeline = make_pipeline(preprocessor, 
                              dtclass
                             )

param_grid = {
    "columntransformer__num_pipe__simpleimputer__strategy":["mean", "median"],
    "decisiontreeclassifier__max_depth": range(2, 14, 2),
    "decisiontreeclassifier__min_samples_leaf": range(3, 12, 2),

}

search = GridSearchCV(full_pipeline,
                      param_grid,
                      cv=5,
                      verbose=0,
                      scoring='accuracy'
                     )

In [24]:
search.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[('num_pipe',
                                                                         Pipeline(steps=[('simpleimputer',
                                                                                          SimpleImputer())]),
                                                                         Index(['LotArea', 'LotFrontage', 'TotalBsmtSF', 'BedroomAbvGr', 'Fireplaces',
       'PoolArea', 'GarageCars', 'WoodDeckSF', 'ScreenPorch'],
      dtype='object')),
                                                                        ('cat_pipe',
                                                                         Pipeline(steps=[('simpleimputer',
                                                                                          Si...
                                                                         Index(['MSZoning', 'Condition1', 'Heating', 'Street', 'CentralAir',
       'Foundation'],
      dtype='object'))])),
                                       ('decisiontreeclassifier',
                                        DecisionTreeClassifier())]),
             param_grid={'columntransformer__num_pipe__simpleimputer__strategy': ['mean',
                                                                                  'median'],
                         'decisiontreeclassifier__max_depth': range(2, 14, 2),
                         'decisiontreeclassifier__min_samples_leaf': range(3, 12, 2)},
             scoring='accuracy')

In [25]:
search.best_score_

0.9186640255309783

In [26]:
search.best_params_

{'columntransformer__num_pipe__simpleimputer__strategy': 'mean',
 'decisiontreeclassifier__max_depth': 4,
 'decisiontreeclassifier__min_samples_leaf': 11}

In [27]:
search.cv_results_['mean_test_score']

array([0.91265544, 0.91265544, 0.91265544, 0.91265544, 0.91265544,
       0.91181175, 0.91523789, 0.91523422, 0.91694729, 0.91866403,
       0.90067496, 0.91265544, 0.90838927, 0.90924397, 0.91352115,
       0.90067863, 0.91094604, 0.90838927, 0.9058105 , 0.91352115,
       0.89468105, 0.9109387 , 0.90924764, 0.9058105 , 0.91010234,
       0.89382635, 0.910084  , 0.90753824, 0.9058105 , 0.91352115,
       0.91265544, 0.91265544, 0.91265544, 0.91265544, 0.91265544,
       0.91181541, 0.91609259, 0.91694362, 0.91694729, 0.91866403,
       0.90067496, 0.91265544, 0.90838927, 0.91095338, 0.91352115,
       0.89467738, 0.91094604, 0.90838927, 0.9075199 , 0.91352115,
       0.89638678, 0.910084  , 0.90753824, 0.9058105 , 0.91010234,
       0.89896189, 0.9075199 , 0.90753824, 0.9058105 , 0.91352115])

In [38]:
# full_pipeline.fit(X_train, y_train)

In [39]:
# from sklearn.metrics import accuracy_score
# y_train_pred = full_pipeline.predict(X_train)

# accuracy_score(y_train, y_train_pred)

In [40]:
full_pipeline.fit(X_test, y_test)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('num_pipe',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer())]),
                                                  Index(['LotArea', 'LotFrontage', 'TotalBsmtSF', 'BedroomAbvGr', 'Fireplaces',
       'PoolArea', 'GarageCars', 'WoodDeckSF', 'ScreenPorch'],
      dtype='object')),
                                                 ('cat_pipe',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(fill_value='N_A',
                                                                                 strategy='constant')),
                                                                  ('onehotencoder',
                                                                   OneHotEncoder())]),
                                                  Index(['MSZoning', 'Condition1', 'Heating', 'Street', 'CentralAir',
       'Foundation'],
      dtype='object'))])),
                ('decisiontreeclassifier', DecisionTreeClassifier())])

In [41]:
y_test_pred = full_pipeline.predict(X_test)

accuracy_score(y_test, y_test_pred)

1.0

In [32]:
from sklearn.metrics import mean_squared_error as MSE
# Compute mse_dt train set
mse_dtree = MSE(y_train, y_train_pred)

# Compute rmse_dt
rmse_dtree = mse_dtree**(1/2)

# Print rmse_dt
print("Train set RMSE of dtree: {:.2f}".format(rmse_dtree))

Train set RMSE of dtree: 0.00

In [33]:
# # Compute mse_dt test set
mse_dtree = MSE(y_test, y_test_pred)

# # Compute rmse_dt
rmse_dtree = mse_dtree**(1/2)

# # Print rmse_dt
print("Test set RMSE of dtree: {:.2f}".format(rmse_dtree))

Test set RMSE of dtree: 0.00